### ISSUE TITLE
JSON pact file not generated after the test passes

### ISSUE THREAD

**Issue by agenteo** [DiUS/pact-consumer-swift#16]
Hi,

I am testing a swift2 app, I've setup the MockService and run my test successfully--I can see the mock-service Webrick log being populated--_but_ there is no pacts directory with the json pact file!

The server starts/stops successfully via the scheme pre/post test scripts.

Has anyone seen this before? Any idea to where to look at what's going wrong?

Thanks

**Comment by andrewspinks** [comment]
Hi @agenteo 
What version of the library are you using? There was a bug in the startup script which was causing errors with the latest version of the mock server. It should be fixed in 0.2.0

You can test by manually starting up the mock server and disabling the script from running.
`pact-mock-service start --pact-specification-version 2.0.0 --log "./tmp/pact.log" --pact-dir "./tmp/pacts" -p 1234`

Let me know if you still have issues.

**Comment by agenteo** [comment]
Hi @andrewspinks 

I was on pact-mock_server 0.9, now updated the gem to 0.10

the consumer has always been 0.2

I tried the manual server start--before and after the gem update--I still don't have pact files baked in. A few things I noticed in the log:

`Received Request` followed by `Found matching response`--both matching my expectations and making the app work. Then `Veryfing - interactions matched for example ""`

The first two log entries are good--meaning the app generated and received back payload--but The Empty string in that Verifying is suspicious.

One thing I forgot to mention this behaviour is in an experiment using `XCUIApplication` and not within a swift unit test. The UI test runs within mockService.run.

**Comment by andrewspinks** [comment]
@agenteo There is nothing specific to any test framework, so it should work for a XCUIApplication. 2 things that I can think of which might be causing the problem:
1. The testComplete() function is not be called. This tells the mock server that all requests have completed and it should verify that all expected requests have been performed.
2. The test is exiting before all the requests have been processed. The mock server processing and your api requests will be asynchronous, so the test needs to be told to wait until everything has finished.  i.e. using something like `waitForExpectationsWithTimeout(5.0, handler:nil)` https://www.bignerdranch.com/blog/asynchronous-testing-with-xcode-6/

**Comment by angelolloqui** [comment]
Check my PR #33
